/**
 * Bounded-memory passage embedding for code-intel semantic snapshots.
 *
 * chunks.jsonl is produced by the native build grouped by path, so passages
 * are generated by reading each source file exactly once, splitting it once,
 * and flushing small text batches through the shared embed worker as we go.
 * Neither all texts nor all rows are ever held in memory; the matrix and
 * ledger are written incrementally into caller-owned staging files.
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { isEnoent } from "@oh-my-pi/pi-utils";
import type { MnemopiSubprocessEmbeddingModel } from "../mnemopi/embed-client";
import { collectEmbedMatrix } from "./code-intel-embed";

/** Chunk shape consumed from chunks.jsonl; full original lines are preserved verbatim in the ledger. */
export interface EmbedChunkRef {
	path: string;
	start_line: number;
	end_line: number;
	symbol: string;
	kind: string;
}

/** Budgets that bound the semantic embed pipeline. Generous defaults so a normal index passes untouched. */
export interface EmbedPassageLimits {
	/** Cap on distinct files whose chunks are embedded (existing maxEmbedFiles setting). */
	maxEmbedFiles: number;
	/** Per-source-file byte cap; larger files abort the embed with an explicit gap. */
	maxFileBytes: number;
	/** Cap on chunks processed for embedding. */
	maxChunks: number;
	/** Cap on total passage-text bytes across the whole embed. */
	maxTotalBytes: number;
	/** In-flight passage text bytes allowed before a batch is flushed. */
	inflightBytes: number;
	/** Passage batch size handed to the embed worker. */
	passageBatchSize: number;
}

export const EMBED_DEFAULT_LIMITS: EmbedPassageLimits = {
	maxEmbedFiles: 4_000,
	maxFileBytes: 32 * 1024 * 1024,
	maxChunks: 500_000,
	maxTotalBytes: 2 * 1024 * 1024 * 1024,
	inflightBytes: 8 * 1024 * 1024,
	passageBatchSize: 32,
};

export interface SemanticEmbedOutcome {
	rows: number;
	dim: number;
	files: number;
	chunks: number;
	totalBytes: number;
}

/** Thrown when a configured budget is exceeded; native snapshot stays intact and a gap is reported. */
export class CodeIntelEmbedBudgetError extends Error {}

function throwIfAborted(signal?: AbortSignal): void {
	if (signal?.aborted) throw new Error("code-intel warm cancelled");
}

async function* iterChunkLines(filePath: string, signal?: AbortSignal): AsyncGenerator<string> {
	const decoder = new TextDecoder();
	let buffer = "";
	try {
		for await (const chunk of Bun.file(filePath).stream()) {
			throwIfAborted(signal);
			buffer += decoder.decode(chunk, { stream: true });
			let nl = buffer.indexOf("\n");
			while (nl >= 0) {
				const line = buffer.slice(0, nl).trim();
				buffer = buffer.slice(nl + 1);
				if (line) yield line;
				nl = buffer.indexOf("\n");
			}
		}
	} catch (error) {
		if (!isEnoent(error)) throw error;
	}
	buffer += decoder.decode();
	const tail = buffer.trim();
	if (tail) yield tail;
}

async function writeAll(file: fs.FileHandle, data: Uint8Array): Promise<void> {
	let offset = 0;
	while (offset < data.byteLength) {
		const { bytesWritten } = await file.write(data, offset, data.byteLength - offset);
		if (bytesWritten === 0) throw new Error("code-intel snapshot write made no progress");
		offset += bytesWritten;
	}
}

/**
 * Streams chunks.jsonl grouped by path, reading each source file at most once,
 * and embeds passages in bounded batches into {@link options.matrixPath} and
 * {@link options.ledgerPath}. Rows are written row-for-row with the verbatim
 * chunk lines, so the published ledger is byte-identical to the input chunks.
 *
 * Throws on budget breach, row/dimension mismatch, or cancellation; the caller
 * keeps or discards the staging files as appropriate.
 */
export async function streamEmbedPassages(options: {
	root: string;
	chunksPath: string;
	handle: MnemopiSubprocessEmbeddingModel;
	limits: EmbedPassageLimits;
	matrixPath: string;
	ledgerPath: string;
	signal?: AbortSignal;
	/** Test seam: overrides the default one-shot source read. */
	readSource?: (absolutePath: string) => Promise<string>;
}): Promise<SemanticEmbedOutcome> {
	const {
		root,
		chunksPath,
		handle,
		limits,
		matrixPath,
		ledgerPath,
		signal,
		readSource = async (absolutePath: string) =>
			Bun.file(absolutePath)
				.slice(0, limits.maxFileBytes + 1)
				.text(),
	} = options;
	const matrix = await fs.open(matrixPath, "w");
	const ledger = await fs.open(ledgerPath, "w").catch(async error => {
		await matrix.close();
		throw error;
	});
	const encoder = new TextEncoder();

	let dim = 0;
	let rows = 0;
	let files = 0;
	let chunks = 0;
	let totalBytes = 0;

	let currentPath: string | null = null;
	let currentChunkLines: string[] = [];
	let batchTexts: string[] = [];
	let batchLines: string[] = [];
	let batchBytes = 0;

	const flushBatch = async (): Promise<void> => {
		if (batchTexts.length === 0) return;
		const batch = batchTexts;
		const batchLedger = batchLines;
		batchTexts = [];
		batchLines = [];
		batchBytes = 0;
		const returned = await collectEmbedMatrix(handle, batch, "passage", limits.passageBatchSize, signal);
		throwIfAborted(signal);
		if (returned.length !== batch.length) {
			throw new Error(`code-intel embed rows mismatch: got ${returned.length}, expected ${batch.length}`);
		}
		if (dim === 0) dim = returned[0]?.length ?? 0;
		if (dim <= 0) throw new Error("code-intel embed model returned zero-dimension rows");
		for (const row of returned) {
			if (row.length !== dim || row.some(value => !Number.isFinite(value))) {
				throw new Error("code-intel embed row dimension mismatch or non-finite value");
			}
		}
		const floats = new Float32Array(batch.length * dim);
		for (let i = 0; i < batch.length; i++) floats.set(Float32Array.from(returned[i]!), i * dim);
		const view = new Uint8Array(floats.buffer, floats.byteOffset, floats.byteLength);
		await writeAll(matrix, view);
		await writeAll(ledger, encoder.encode(`${batchLedger.join("\n")}\n`));
		rows += batch.length;
		await Bun.sleep(0);
	};

	const embedFile = async (): Promise<void> => {
		const filePath = currentPath;
		const chunkLines = currentChunkLines;
		currentPath = null;
		currentChunkLines = [];
		if (filePath === null || chunkLines.length === 0) return;
		throwIfAborted(signal);
		files += 1;
		const absolute = path.resolve(root, filePath);
		let source: string;
		try {
			const stat = await fs.stat(absolute);
			if (stat.size > limits.maxFileBytes) {
				throw new CodeIntelEmbedBudgetError(
					`code-intel embed file "${filePath}" exceeds per-file budget (${stat.size} > ${limits.maxFileBytes} bytes)`,
				);
			}
			source = await readSource(absolute);
			if (Buffer.byteLength(source) > limits.maxFileBytes) {
				throw new CodeIntelEmbedBudgetError(`code-intel embed source exceeds per-file budget: ${filePath}`);
			}
		} catch (error) {
			if (signal?.aborted) throw error;
			if (isEnoent(error) || (error as NodeJS.ErrnoException).code === "ENOENT") {
				source = "";
			} else {
				throw error;
			}
		}
		const lines = source.split("\n");
		for (const line of chunkLines) {
			throwIfAborted(signal);
			const chunk = JSON.parse(line) as EmbedChunkRef;
			chunks += 1;
			if (chunks > limits.maxChunks) {
				throw new CodeIntelEmbedBudgetError(
					`code-intel embed chunk budget exceeded (max ${limits.maxChunks} chunks)`,
				);
			}
			const from = Math.max(0, chunk.start_line - 1);
			const to = Math.min(lines.length, Math.max(from + 1, chunk.end_line));
			const body = lines.slice(from, to).join("\n").trim();
			const text = body
				? `${chunk.kind} ${chunk.symbol}\n${chunk.path}\n${body}`
				: `${chunk.kind} ${chunk.symbol}\n${chunk.path}`;
			const textBytes = Buffer.byteLength(text);
			if (textBytes > limits.inflightBytes) {
				throw new CodeIntelEmbedBudgetError("code-intel embed passage exceeds in-flight byte budget");
			}
			totalBytes += textBytes;
			if (totalBytes > limits.maxTotalBytes) {
				throw new CodeIntelEmbedBudgetError(
					`code-intel embed total budget exceeded (max ${limits.maxTotalBytes} passage bytes)`,
				);
			}
			if (batchBytes + textBytes > limits.inflightBytes) await flushBatch();
			batchTexts.push(text);
			batchLines.push(line);
			batchBytes += textBytes;
			if (batchTexts.length >= limits.passageBatchSize || batchBytes >= limits.inflightBytes) {
				await flushBatch();
			}
		}
	};

	try {
		for await (const line of iterChunkLines(chunksPath, signal)) {
			throwIfAborted(signal);
			const chunk = JSON.parse(line) as EmbedChunkRef;
			if (chunk.path !== currentPath) {
				await embedFile();
				if (files >= limits.maxEmbedFiles) break;
				currentPath = chunk.path;
			}
			if (chunks + currentChunkLines.length >= limits.maxChunks) {
				throw new CodeIntelEmbedBudgetError(
					`code-intel embed chunk budget exceeded (max ${limits.maxChunks} chunks)`,
				);
			}
			currentChunkLines.push(line);
		}
		await embedFile();
		await flushBatch();
		return { rows, dim, files, chunks, totalBytes };
	} finally {
		await matrix.close().catch(() => undefined);
		await ledger.close().catch(() => undefined);
	}
}
