import type { ModelProfile } from "./types";

export const DEFAULT_MODEL_PROFILES = {
	claude_planner: {
		id: "claude_planner",
		vendor: "anthropic",
		modelPattern: ["claude-sonnet-*", "claude-opus-*"],
		roles: ["planner"],
		promptTemplate: "planner",
		promptVersion: "1.0",
		toolPolicyId: "readonly-planning",
		maxRequests: 50,
		maxRuntimeMs: 300_000,
		retryPolicy: {
			maxAttempts: 2,
			retryableErrorKinds: ["timeout", "rate_limit"],
			fallbackProfileIds: ["gpt_planner"],
		},
		contextPolicy: {
			includePlan: true,
			includeReviewFindings: true,
			includeVerification: true,
			includeFullTranscript: false,
			maxArtifactBytes: 1024 * 1024,
		},
	},
	gpt_planner: {
		id: "gpt_planner",
		vendor: "openai",
		modelPattern: ["gpt-5.*", "o3*"],
		roles: ["planner"],
		promptTemplate: "planner",
		promptVersion: "1.0",
		toolPolicyId: "readonly-planning",
		maxRequests: 50,
		maxRuntimeMs: 300_000,
		retryPolicy: { maxAttempts: 2, retryableErrorKinds: ["timeout", "rate_limit"], fallbackProfileIds: [] },
		contextPolicy: {
			includePlan: true,
			includeReviewFindings: true,
			includeVerification: true,
			includeFullTranscript: false,
			maxArtifactBytes: 1024 * 1024,
		},
	},
	grok_implementer: {
		id: "grok_implementer",
		vendor: "xai",
		modelPattern: ["grok-code-*", "grok-4*"],
		roles: ["implementer"],
		promptTemplate: "implementer",
		promptVersion: "1.0",
		toolPolicyId: "scoped-implementation",
		maxRequests: 200,
		maxRuntimeMs: 600_000,
		retryPolicy: { maxAttempts: 1, retryableErrorKinds: [], fallbackProfileIds: [] },
		contextPolicy: {
			includePlan: true,
			includeReviewFindings: false,
			includeVerification: true,
			includeFullTranscript: false,
			maxArtifactBytes: 1024 * 1024,
		},
	},
	claude_reviewer: {
		id: "claude_reviewer",
		vendor: "anthropic",
		modelPattern: ["claude-sonnet-*", "claude-opus-*"],
		roles: ["plan_reviewer", "code_reviewer"],
		promptTemplate: "independent-reviewer",
		promptVersion: "1.0",
		toolPolicyId: "readonly-review",
		maxRequests: 50,
		maxRuntimeMs: 180_000,
		retryPolicy: { maxAttempts: 2, retryableErrorKinds: ["timeout"], fallbackProfileIds: ["gpt_reviewer"] },
		contextPolicy: {
			includePlan: true,
			includeReviewFindings: true,
			includeVerification: true,
			includeFullTranscript: true,
			maxArtifactBytes: 2 * 1024 * 1024,
		},
	},
	gpt_reviewer: {
		id: "gpt_reviewer",
		vendor: "openai",
		modelPattern: ["gpt-5.*", "o3*"],
		roles: ["plan_reviewer", "code_reviewer", "repair"],
		promptTemplate: "independent-reviewer",
		promptVersion: "1.0",
		toolPolicyId: "readonly-review",
		maxRequests: 50,
		maxRuntimeMs: 180_000,
		retryPolicy: { maxAttempts: 2, retryableErrorKinds: ["timeout"], fallbackProfileIds: [] },
		contextPolicy: {
			includePlan: true,
			includeReviewFindings: true,
			includeVerification: true,
			includeFullTranscript: true,
			maxArtifactBytes: 2 * 1024 * 1024,
		},
	},
} satisfies Record<string, ModelProfile>;

export function getDefaultConfig() {
	return {
		defaultRole: "implementer" as const,
		degradedMode: false,
		maxBudgetUsd: 10,
		maxAttempts: 3,
		profiles: DEFAULT_MODEL_PROFILES,
	};
}
